from app import db
from app.models import Course, Day, Room, CourseCount, MondayRoomAvailability, TuesdayRoomAvailability,ThursdayRoomAvailability,WednesdayRoomAvailability,FridayRoomAvailability,SaturdayRoomAvailability


day1 = Day(day_id="Mon",day_name="Monday")
day2 = Day(day_id="Tues",day_name="Tuesday")
day3 = Day(day_id="Wed",day_name="Wednesday")
day4 = Day(day_id="Thur",day_name="Thursday")
day5 = Day(day_id="Fri",day_name="Friday")
day6 = Day(day_id="Sat",day_name="Saturday")

db.session.add(day1)
db.session.commit()
db.session.add(day2)
db.session.commit()
db.session.add(day3)
db.session.commit()
db.session.add(day4)
db.session.commit()
db.session.add(day5)
db.session.commit()
db.session.add(day6)
db.session.commit()

course1 = Course(course_id="COMP2211", course_name="Analysis of Algorithms")
course2 = Course(course_id="COMP2201", course_name="Discrete Mathematics")
course3 = Course(course_id="COMP2190", course_name="Net-Centric Computing")
course4 = Course(course_id="COMP3191", course_name="Principles of Computer Networking")
course5 = Course(course_id="COMP3702", course_name="Theory of Computations")
course6 = Course(course_id="COMP3161", course_name="Database Management Systems")
course7 = Course(course_id="INFO2100", course_name="Math and Statistics for IT")
course8 = Course(course_id="INFO2110", course_name="Data Structures for IT")
course9 = Course(course_id="INFO3155", course_name="Information Assurance and Security")
course10 = Course(course_id="INFO3180", course_name="Dynamic Web Develoopment 2")

db.session.add(course1)
db.session.commit()
db.session.add(course2)
db.session.commit()
db.session.add(course3)
db.session.commit()
db.session.add(course4)
db.session.commit()
db.session.add(course5)
db.session.commit()
db.session.add(course6)
db.session.commit()
db.session.add(course7)
db.session.commit()
db.session.add(course8)
db.session.commit()
db.session.add(course9)
db.session.commit()
db.session.add(course10)
db.session.commit()

room1 = Room(room_id = "SLT1", room_name = "Science Lecture Theatre 1")
room2 = Room(room_id = "SLT2", room_name = "Science Lecture Theatre 2")
room3 = Room(room_id = "SLT3", room_name = "Science Lecture Theatre 3")
room4 = Room(room_id = "CR1", room_name = "Computing Tutorial 1")
room5 = Room(room_id = "CR2", room_name = "Computing Tutorial 2")
room6 = Room(room_id = "PG1", room_name = "Postgraduate Lecture Room")
room7 = Room(room_id = "PG2", room_name = "Postgraduate Lab")
room8 = Room(room_id = "CL", room_name = "Computing Lecture Room")

db.session.add(room1)
db.session.commit()
db.session.add(room2)
db.session.commit()
db.session.add(room3)
db.session.commit()
db.session.add(room4)
db.session.commit()
db.session.add(room5)
db.session.commit()
db.session.add(room6)
db.session.commit()
db.session.add(room7)
db.session.commit()
db.session.add(room8)
db.session.commit()

course1 = CourseCount(course_id="COMP2211", count_tutors=0)
course2 = CourseCount(course_id="COMP2201", count_tutors=0)
course3 = CourseCount(course_id="COMP2190", count_tutors=0)
course4 = CourseCount(course_id="COMP3191", count_tutors=0)
course5 = CourseCount(course_id="COMP3702", count_tutors=0)
course6 = CourseCount(course_id="COMP3161", count_tutors=0)
course7 = CourseCount(course_id="INFO2100", count_tutors=0)
course8 = CourseCount(course_id="INFO2110", count_tutors=0)
course9 = CourseCount(course_id="INFO3155", count_tutors=0)
course10 = CourseCount(course_id="INFO3180", count_tutors=0)

db.session.add(course1)
db.session.commit()
db.session.add(course2)
db.session.commit()
db.session.add(course3)
db.session.commit()
db.session.add(course4)
db.session.commit()
db.session.add(course5)
db.session.commit()
db.session.add(course6)
db.session.commit()
db.session.add(course7)
db.session.commit()
db.session.add(course8)
db.session.commit()
db.session.add(course9)
db.session.commit()
db.session.add(course10)
db.session.commit()

ava1=MondayRoomAvailability(room_id='SLT1', time=9, status = "")
ava2=MondayRoomAvailability(room_id='SLT1', time=12, status = "")
ava3=MondayRoomAvailability(room_id='SLT1', time=17, status = "")
ava4=MondayRoomAvailability(room_id='SLT2', time=8, status = "")
ava5=MondayRoomAvailability(room_id='SLT2', time=14, status = "")
ava6=MondayRoomAvailability(room_id='SLT2', time=15, status = "")
ava7=MondayRoomAvailability(room_id='SLT2', time=19, status = "")
ava8=MondayRoomAvailability(room_id='SLT2', time=20, status = "")
ava9=MondayRoomAvailability(room_id='SLT3', time=8, status = "")
ava10=MondayRoomAvailability(room_id='SLT3', time=9, status = "")
ava11=MondayRoomAvailability(room_id='SLT3', time=17, status = "")
ava12=MondayRoomAvailability(room_id='CR1', time=15, status = "")
ava13=MondayRoomAvailability(room_id='CR1', time=17, status = "")
ava14=MondayRoomAvailability(room_id='CR2', time=10, status = "")
ava15=MondayRoomAvailability(room_id='CR2', time=12, status = "")
ava16=MondayRoomAvailability(room_id='CR2', time=13, status = "")
ava17=MondayRoomAvailability(room_id='CR2', time=18, status = "")
ava18=MondayRoomAvailability(room_id='PG1', time=8, status = "")
ava19=MondayRoomAvailability(room_id='PG1', time=10, status = "")
ava20=MondayRoomAvailability(room_id='PG1', time=13, status = "")
ava21=MondayRoomAvailability(room_id='PG1', time=14, status = "")
ava22=MondayRoomAvailability(room_id='PG1', time=17, status = "")
ava23=MondayRoomAvailability(room_id='PG1', time=18, status = "")
ava24=MondayRoomAvailability(room_id='PG2', time=8, status = "")
ava25=MondayRoomAvailability(room_id='PG2', time=9, status = "")
ava26=MondayRoomAvailability(room_id='PG2', time=10, status = "")
ava27=MondayRoomAvailability(room_id='PG2', time=11, status = "")
ava28=MondayRoomAvailability(room_id='PG2', time=16, status = "")
ava29=MondayRoomAvailability(room_id='PG2', time=17, status = "")
ava30=MondayRoomAvailability(room_id='PG2', time=18, status = "")
ava31=MondayRoomAvailability(room_id='PG2', time=19, status = "")
ava32=MondayRoomAvailability(room_id='PG2', time=20, status = "")
ava33=MondayRoomAvailability(room_id='CL', time=11, status = "")
ava34=MondayRoomAvailability(room_id='CL', time=14, status = "")
ava35=MondayRoomAvailability(room_id='CL', time=15, status = "")
ava36=MondayRoomAvailability(room_id='CL', time=18, status = "")
ava37=MondayRoomAvailability(room_id='CL', time=19, status = "")

db.session.add(ava1)
db.session.commit()
db.session.add(ava2)
db.session.commit()
db.session.add(ava3)
db.session.commit()
db.session.add(ava4)
db.session.commit()
db.session.add(ava5)
db.session.commit()
db.session.add(ava6)
db.session.commit()
db.session.add(ava7)
db.session.commit()
db.session.add(ava8)
db.session.commit()
db.session.add(ava9)
db.session.commit()
db.session.add(ava10)
db.session.commit()
db.session.add(ava11)
db.session.commit()
db.session.add(ava12)
db.session.commit()
db.session.add(ava13)
db.session.commit()
db.session.add(ava14)
db.session.commit()
db.session.add(ava15)
db.session.commit()
db.session.add(ava16)
db.session.commit()
db.session.add(ava17)
db.session.commit()
db.session.add(ava18)
db.session.commit()
db.session.add(ava19)
db.session.commit()
db.session.add(ava20)
db.session.commit()
db.session.add(ava21)
db.session.commit()
db.session.add(ava22)
db.session.commit()
db.session.add(ava23)
db.session.commit()
db.session.add(ava24)
db.session.commit()
db.session.add(ava25)
db.session.commit()
db.session.add(ava26)
db.session.commit()
db.session.add(ava27)
db.session.commit()
db.session.add(ava28)
db.session.commit()
db.session.add(ava29)
db.session.commit()
db.session.add(ava30)
db.session.commit()
db.session.add(ava31)
db.session.commit()
db.session.add(ava32)
db.session.commit()
db.session.add(ava33)
db.session.commit()
db.session.add(ava34)
db.session.commit()
db.session.add(ava35)
db.session.commit()
db.session.add(ava36)
db.session.commit()
db.session.add(ava37)
db.session.commit()

#Tuesday

tava1=TuesdayRoomAvailability(room_id='SLT1', time=9, status = "")
tava2=TuesdayRoomAvailability(room_id='SLT1', time=12, status = "")
tava3=TuesdayRoomAvailability(room_id='SLT1', time=17, status = "")
tava4=TuesdayRoomAvailability(room_id='SLT2', time=8, status = "")
tava5=TuesdayRoomAvailability(room_id='SLT2', time=14, status = "")
tava6=TuesdayRoomAvailability(room_id='SLT2', time=15, status = "")
tava7=TuesdayRoomAvailability(room_id='SLT2', time=19, status = "")
tava8=TuesdayRoomAvailability(room_id='SLT2', time=20, status = "")
tava9=TuesdayRoomAvailability(room_id='SLT3', time=8, status = "")
tava10=TuesdayRoomAvailability(room_id='SLT3', time=9, status = "")
tava11=TuesdayRoomAvailability(room_id='SLT3', time=17, status = "")
tava12=TuesdayRoomAvailability(room_id='CR1', time=15, status = "")
tava13=TuesdayRoomAvailability(room_id='CR1', time=17, status = "")
tava14=TuesdayRoomAvailability(room_id='CR2', time=10, status = "")
tava15=TuesdayRoomAvailability(room_id='CR2', time=12, status = "")
tava16=TuesdayRoomAvailability(room_id='CR2', time=13, status = "")
tava17=TuesdayRoomAvailability(room_id='CR2', time=18, status = "")
tava18=TuesdayRoomAvailability(room_id='PG1', time=8, status = "")
tava19=TuesdayRoomAvailability(room_id='PG1', time=10, status = "")
tava20=TuesdayRoomAvailability(room_id='PG1', time=13, status = "")
tava21=TuesdayRoomAvailability(room_id='PG1', time=14, status = "")
tava22=TuesdayRoomAvailability(room_id='PG1', time=17, status = "")
tava23=TuesdayRoomAvailability(room_id='PG1', time=18, status = "")
tava24=TuesdayRoomAvailability(room_id='PG2', time=8, status = "")
tava25=TuesdayRoomAvailability(room_id='PG2', time=9, status = "")
tava26=TuesdayRoomAvailability(room_id='PG2', time=10, status = "")
tava27=TuesdayRoomAvailability(room_id='PG2', time=11, status = "")
tava28=TuesdayRoomAvailability(room_id='PG2', time=16, status = "")
tava29=TuesdayRoomAvailability(room_id='PG2', time=17, status = "")
tava30=TuesdayRoomAvailability(room_id='PG2', time=18, status = "")
tava31=TuesdayRoomAvailability(room_id='PG2', time=19, status = "")
tava32=TuesdayRoomAvailability(room_id='PG2', time=20, status = "")
tava33=TuesdayRoomAvailability(room_id='CL', time=11, status = "")
tava34=TuesdayRoomAvailability(room_id='CL', time=14, status = "")
tava35=TuesdayRoomAvailability(room_id='CL', time=15, status = "")
tava36=TuesdayRoomAvailability(room_id='CL', time=18, status = "")
tava37=TuesdayRoomAvailability(room_id='CL', time=19, status = "")

db.session.add(tava1)
db.session.commit()
db.session.add(tava2)
db.session.commit()
db.session.add(tava3)
db.session.commit()
db.session.add(tava4)
db.session.commit()
db.session.add(tava5)
db.session.commit()
db.session.add(tava6)
db.session.commit()
db.session.add(tava7)
db.session.commit()
db.session.add(tava8)
db.session.commit()
db.session.add(tava9)
db.session.commit()
db.session.add(tava10)
db.session.commit()
db.session.add(tava11)
db.session.commit()
db.session.add(tava12)
db.session.commit()
db.session.add(tava13)
db.session.commit()
db.session.add(tava14)
db.session.commit()
db.session.add(tava15)
db.session.commit()
db.session.add(tava16)
db.session.commit()
db.session.add(tava17)
db.session.commit()
db.session.add(tava18)
db.session.commit()
db.session.add(tava19)
db.session.commit()
db.session.add(tava20)
db.session.commit()
db.session.add(tava21)
db.session.commit()
db.session.add(tava22)
db.session.commit()
db.session.add(tava23)
db.session.commit()
db.session.add(tava24)
db.session.commit()
db.session.add(tava25)
db.session.commit()
db.session.add(tava26)
db.session.commit()
db.session.add(tava27)
db.session.commit()
db.session.add(tava28)
db.session.commit()
db.session.add(tava29)
db.session.commit()
db.session.add(tava30)
db.session.commit()
db.session.add(tava31)
db.session.commit()
db.session.add(tava32)
db.session.commit()
db.session.add(tava33)
db.session.commit()
db.session.add(tava34)
db.session.commit()
db.session.add(tava35)
db.session.commit()
db.session.add(tava36)
db.session.commit()
db.session.add(tava37)
db.session.commit()


#Wednesday

wava1=WednesdayRoomAvailability(room_id='SLT1', time=9, status = "")
wava2=WednesdayRoomAvailability(room_id='SLT1', time=12, status = "")
wava3=WednesdayRoomAvailability(room_id='SLT1', time=17, status = "")
wava4=WednesdayRoomAvailability(room_id='SLT2', time=8, status = "")
wava5=WednesdayRoomAvailability(room_id='SLT2', time=14, status = "")
wava6=WednesdayRoomAvailability(room_id='SLT2', time=15, status = "")
wava7=WednesdayRoomAvailability(room_id='SLT2', time=19, status = "")
wava8=WednesdayRoomAvailability(room_id='SLT2', time=20, status = "")
wava9=WednesdayRoomAvailability(room_id='SLT3', time=8, status = "")
wava10=WednesdayRoomAvailability(room_id='SLT3', time=9, status = "")
wava11=WednesdayRoomAvailability(room_id='SLT3', time=17, status = "")
wava12=WednesdayRoomAvailability(room_id='CR1', time=15, status = "")
wava13=WednesdayRoomAvailability(room_id='CR1', time=17, status = "")
wava14=WednesdayRoomAvailability(room_id='CR2', time=10, status = "")
wava15=WednesdayRoomAvailability(room_id='CR2', time=12, status = "")
wava16=WednesdayRoomAvailability(room_id='CR2', time=13, status = "")
wava17=WednesdayRoomAvailability(room_id='CR2', time=18, status = "")
wava18=WednesdayRoomAvailability(room_id='PG1', time=8, status = "")
wava19=WednesdayRoomAvailability(room_id='PG1', time=10, status = "")
wava20=WednesdayRoomAvailability(room_id='PG1', time=13, status = "")
wava21=WednesdayRoomAvailability(room_id='PG1', time=14, status = "")
wava22=WednesdayRoomAvailability(room_id='PG1', time=17, status = "")
wava23=WednesdayRoomAvailability(room_id='PG1', time=18, status = "")
wava24=WednesdayRoomAvailability(room_id='PG2', time=8, status = "")
wava25=WednesdayRoomAvailability(room_id='PG2', time=9, status = "")
wava26=WednesdayRoomAvailability(room_id='PG2', time=10, status = "")
wava27=WednesdayRoomAvailability(room_id='PG2', time=11, status = "")
wava28=WednesdayRoomAvailability(room_id='PG2', time=16, status = "")
wava29=WednesdayRoomAvailability(room_id='PG2', time=17, status = "")
wava30=WednesdayRoomAvailability(room_id='PG2', time=18, status = "")
wava31=WednesdayRoomAvailability(room_id='PG2', time=19, status = "")
wava32=WednesdayRoomAvailability(room_id='PG2', time=20, status = "")
wava33=WednesdayRoomAvailability(room_id='CL', time=11, status = "")
wava34=WednesdayRoomAvailability(room_id='CL', time=14, status = "")
wava35=WednesdayRoomAvailability(room_id='CL', time=15, status = "")
wava36=WednesdayRoomAvailability(room_id='CL', time=18, status = "")
wava37=WednesdayRoomAvailability(room_id='CL', time=19, status = "")

db.session.add(wava1)
db.session.commit()
db.session.add(wava2)
db.session.commit()
db.session.add(wava3)
db.session.commit()
db.session.add(wava4)
db.session.commit()
db.session.add(wava5)
db.session.commit()
db.session.add(wava6)
db.session.commit()
db.session.add(wava7)
db.session.commit()
db.session.add(wava8)
db.session.commit()
db.session.add(wava9)
db.session.commit()
db.session.add(wava10)
db.session.commit()
db.session.add(wava11)
db.session.commit()
db.session.add(wava12)
db.session.commit()
db.session.add(wava13)
db.session.commit()
db.session.add(wava14)
db.session.commit()
db.session.add(wava15)
db.session.commit()
db.session.add(wava16)
db.session.commit()
db.session.add(wava17)
db.session.commit()
db.session.add(wava18)
db.session.commit()
db.session.add(wava19)
db.session.commit()
db.session.add(wava20)
db.session.commit()
db.session.add(wava21)
db.session.commit()
db.session.add(wava22)
db.session.commit()
db.session.add(wava23)
db.session.commit()
db.session.add(wava24)
db.session.commit()
db.session.add(wava25)
db.session.commit()
db.session.add(wava26)
db.session.commit()
db.session.add(wava27)
db.session.commit()
db.session.add(wava28)
db.session.commit()
db.session.add(wava29)
db.session.commit()
db.session.add(wava30)
db.session.commit()
db.session.add(wava31)
db.session.commit()
db.session.add(wava32)
db.session.commit()
db.session.add(wava33)
db.session.commit()
db.session.add(wava34)
db.session.commit()
db.session.add(wava35)
db.session.commit()
db.session.add(wava36)
db.session.commit()
db.session.add(wava37)
db.session.commit()


#Thursday

rava1=ThursdayRoomAvailability(room_id='SLT1', time=9, status = "")
rava2=ThursdayRoomAvailability(room_id='SLT1', time=12, status = "")
rava3=ThursdayRoomAvailability(room_id='SLT1', time=17, status = "")
rava4=ThursdayRoomAvailability(room_id='SLT2', time=8, status = "")
rava5=ThursdayRoomAvailability(room_id='SLT2', time=14, status = "")
rava6=ThursdayRoomAvailability(room_id='SLT2', time=15, status = "")
rava7=ThursdayRoomAvailability(room_id='SLT2', time=19, status = "")
rava8=ThursdayRoomAvailability(room_id='SLT2', time=20, status = "")
rava9=ThursdayRoomAvailability(room_id='SLT3', time=8, status = "")
rava10=ThursdayRoomAvailability(room_id='SLT3', time=9, status = "")
rava11=ThursdayRoomAvailability(room_id='SLT3', time=17, status = "")
rava12=ThursdayRoomAvailability(room_id='CR1', time=15, status = "")
rava13=ThursdayRoomAvailability(room_id='CR1', time=17, status = "")
rava14=ThursdayRoomAvailability(room_id='CR2', time=10, status = "")
rava15=ThursdayRoomAvailability(room_id='CR2', time=12, status = "")
rava16=ThursdayRoomAvailability(room_id='CR2', time=13, status = "")
rava17=ThursdayRoomAvailability(room_id='CR2', time=18, status = "")
rava18=ThursdayRoomAvailability(room_id='PG1', time=8, status = "")
rava19=ThursdayRoomAvailability(room_id='PG1', time=10, status = "")
rava20=ThursdayRoomAvailability(room_id='PG1', time=13, status = "")
rava21=ThursdayRoomAvailability(room_id='PG1', time=14, status = "")
rava22=ThursdayRoomAvailability(room_id='PG1', time=17, status = "")
rava23=ThursdayRoomAvailability(room_id='PG1', time=18, status = "")
rava24=ThursdayRoomAvailability(room_id='PG2', time=8, status = "")
rava25=ThursdayRoomAvailability(room_id='PG2', time=9, status = "")
rava26=ThursdayRoomAvailability(room_id='PG2', time=10, status = "")
rava27=ThursdayRoomAvailability(room_id='PG2', time=11, status = "")
rava28=ThursdayRoomAvailability(room_id='PG2', time=16, status = "")
rava29=ThursdayRoomAvailability(room_id='PG2', time=17, status = "")
rava30=ThursdayRoomAvailability(room_id='PG2', time=18, status = "")
rava31=ThursdayRoomAvailability(room_id='PG2', time=19, status = "")
rava32=ThursdayRoomAvailability(room_id='PG2', time=20, status = "")
rava33=ThursdayRoomAvailability(room_id='CL', time=11, status = "")
rava34=ThursdayRoomAvailability(room_id='CL', time=14, status = "")
rava35=ThursdayRoomAvailability(room_id='CL', time=15, status = "")
rava36=ThursdayRoomAvailability(room_id='CL', time=18, status = "")
rava37=ThursdayRoomAvailability(room_id='CL', time=19, status = "")

db.session.add(rava1)
db.session.commit()
db.session.add(rava2)
db.session.commit()
db.session.add(rava3)
db.session.commit()
db.session.add(rava4)
db.session.commit()
db.session.add(rava5)
db.session.commit()
db.session.add(rava6)
db.session.commit()
db.session.add(rava7)
db.session.commit()
db.session.add(rava8)
db.session.commit()
db.session.add(rava9)
db.session.commit()
db.session.add(rava10)
db.session.commit()
db.session.add(rava11)
db.session.commit()
db.session.add(rava12)
db.session.commit()
db.session.add(rava13)
db.session.commit()
db.session.add(rava14)
db.session.commit()
db.session.add(rava15)
db.session.commit()
db.session.add(rava16)
db.session.commit()
db.session.add(rava17)
db.session.commit()
db.session.add(rava18)
db.session.commit()
db.session.add(rava19)
db.session.commit()
db.session.add(rava20)
db.session.commit()
db.session.add(rava21)
db.session.commit()
db.session.add(rava22)
db.session.commit()
db.session.add(rava23)
db.session.commit()
db.session.add(rava24)
db.session.commit()
db.session.add(rava25)
db.session.commit()
db.session.add(rava26)
db.session.commit()
db.session.add(rava27)
db.session.commit()
db.session.add(rava28)
db.session.commit()
db.session.add(rava29)
db.session.commit()
db.session.add(rava30)
db.session.commit()
db.session.add(rava31)
db.session.commit()
db.session.add(rava32)
db.session.commit()
db.session.add(rava33)
db.session.commit()
db.session.add(rava34)
db.session.commit()
db.session.add(rava35)
db.session.commit()
db.session.add(rava36)
db.session.commit()
db.session.add(rava37)
db.session.commit()


#Friday

fava1=FridayRoomAvailability(room_id='SLT1', time=9, status = "")
fava2=FridayRoomAvailability(room_id='SLT1', time=12, status = "")
fava3=FridayRoomAvailability(room_id='SLT1', time=17, status = "")
fava4=FridayRoomAvailability(room_id='SLT2', time=8, status = "")
fava5=FridayRoomAvailability(room_id='SLT2', time=14, status = "")
fava6=FridayRoomAvailability(room_id='SLT2', time=15, status = "")
fava7=FridayRoomAvailability(room_id='SLT2', time=19, status = "")
fava8=FridayRoomAvailability(room_id='SLT2', time=20, status = "")
fava9=FridayRoomAvailability(room_id='SLT3', time=8, status = "")
fava10=FridayRoomAvailability(room_id='SLT3', time=9, status = "")
fava11=FridayRoomAvailability(room_id='SLT3', time=17, status = "")
fava12=FridayRoomAvailability(room_id='CR1', time=15, status = "")
fava13=FridayRoomAvailability(room_id='CR1', time=17, status = "")
fava14=FridayRoomAvailability(room_id='CR2', time=10, status = "")
fava15=FridayRoomAvailability(room_id='CR2', time=12, status = "")
fava16=FridayRoomAvailability(room_id='CR2', time=13, status = "")
fava17=FridayRoomAvailability(room_id='CR2', time=18, status = "")
fava18=FridayRoomAvailability(room_id='PG1', time=8, status = "")
fava19=FridayRoomAvailability(room_id='PG1', time=10, status = "")
fava20=FridayRoomAvailability(room_id='PG1', time=13, status = "")
fava21=FridayRoomAvailability(room_id='PG1', time=14, status = "")
fava22=FridayRoomAvailability(room_id='PG1', time=17, status = "")
fava23=FridayRoomAvailability(room_id='PG1', time=18, status = "")
fava24=FridayRoomAvailability(room_id='PG2', time=8, status = "")
fava25=FridayRoomAvailability(room_id='PG2', time=9, status = "")
fava26=FridayRoomAvailability(room_id='PG2', time=10, status = "")
fava27=FridayRoomAvailability(room_id='PG2', time=11, status = "")
fava28=FridayRoomAvailability(room_id='PG2', time=16, status = "")
fava29=FridayRoomAvailability(room_id='PG2', time=17, status = "")
fava30=FridayRoomAvailability(room_id='PG2', time=18, status = "")
fava31=FridayRoomAvailability(room_id='PG2', time=19, status = "")
fava32=FridayRoomAvailability(room_id='PG2', time=20, status = "")
fava33=FridayRoomAvailability(room_id='CL', time=11, status = "")
fava34=FridayRoomAvailability(room_id='CL', time=14, status = "")
fava35=FridayRoomAvailability(room_id='CL', time=15, status = "")
fava36=FridayRoomAvailability(room_id='CL', time=18, status = "")
fava37=FridayRoomAvailability(room_id='CL', time=19, status = "")

db.session.add(fava1)
db.session.commit()
db.session.add(fava2)
db.session.commit()
db.session.add(fava3)
db.session.commit()
db.session.add(fava4)
db.session.commit()
db.session.add(fava5)
db.session.commit()
db.session.add(fava6)
db.session.commit()
db.session.add(fava7)
db.session.commit()
db.session.add(fava8)
db.session.commit()
db.session.add(fava9)
db.session.commit()
db.session.add(fava10)
db.session.commit()
db.session.add(fava11)
db.session.commit()
db.session.add(fava12)
db.session.commit()
db.session.add(fava13)
db.session.commit()
db.session.add(fava14)
db.session.commit()
db.session.add(fava15)
db.session.commit()
db.session.add(fava16)
db.session.commit()
db.session.add(fava17)
db.session.commit()
db.session.add(fava18)
db.session.commit()
db.session.add(fava19)
db.session.commit()
db.session.add(fava20)
db.session.commit()
db.session.add(fava21)
db.session.commit()
db.session.add(fava22)
db.session.commit()
db.session.add(fava23)
db.session.commit()
db.session.add(fava24)
db.session.commit()
db.session.add(fava25)
db.session.commit()
db.session.add(fava26)
db.session.commit()
db.session.add(fava27)
db.session.commit()
db.session.add(fava28)
db.session.commit()
db.session.add(fava29)
db.session.commit()
db.session.add(fava30)
db.session.commit()
db.session.add(fava31)
db.session.commit()
db.session.add(fava32)
db.session.commit()
db.session.add(fava33)
db.session.commit()
db.session.add(fava34)
db.session.commit()
db.session.add(fava35)
db.session.commit()
db.session.add(fava36)
db.session.commit()
db.session.add(fava37)
db.session.commit()


#Saturday

sava1=SaturdayRoomAvailability(room_id='SLT1', time=9, status = "")
sava2=SaturdayRoomAvailability(room_id='SLT1', time=12, status = "")
sava3=SaturdayRoomAvailability(room_id='SLT1', time=17, status = "")
sava4=SaturdayRoomAvailability(room_id='SLT2', time=8, status = "")
sava5=SaturdayRoomAvailability(room_id='SLT2', time=14, status = "")
sava6=SaturdayRoomAvailability(room_id='SLT2', time=15, status = "")
sava7=SaturdayRoomAvailability(room_id='SLT2', time=19, status = "")
sava8=SaturdayRoomAvailability(room_id='SLT2', time=20, status = "")
sava9=SaturdayRoomAvailability(room_id='SLT3', time=8, status = "")
sava10=SaturdayRoomAvailability(room_id='SLT3', time=9, status = "")
sava11=SaturdayRoomAvailability(room_id='SLT3', time=17, status = "")
sava12=SaturdayRoomAvailability(room_id='CR1', time=15, status = "")
sava13=SaturdayRoomAvailability(room_id='CR1', time=17, status = "")
sava14=SaturdayRoomAvailability(room_id='CR2', time=10, status = "")
sava15=SaturdayRoomAvailability(room_id='CR2', time=12, status = "")
sava16=SaturdayRoomAvailability(room_id='CR2', time=13, status = "")
sava17=SaturdayRoomAvailability(room_id='CR2', time=18, status = "")
sava18=SaturdayRoomAvailability(room_id='PG1', time=8, status = "")
sava19=SaturdayRoomAvailability(room_id='PG1', time=10, status = "")
sava20=SaturdayRoomAvailability(room_id='PG1', time=13, status = "")
sava21=SaturdayRoomAvailability(room_id='PG1', time=14, status = "")
sava22=SaturdayRoomAvailability(room_id='PG1', time=17, status = "")
sava23=SaturdayRoomAvailability(room_id='PG1', time=18, status = "")
sava24=SaturdayRoomAvailability(room_id='PG2', time=8, status = "")
sava25=SaturdayRoomAvailability(room_id='PG2', time=9, status = "")
sava26=SaturdayRoomAvailability(room_id='PG2', time=10, status = "")
sava27=SaturdayRoomAvailability(room_id='PG2', time=11, status = "")
sava28=SaturdayRoomAvailability(room_id='PG2', time=16, status = "")
sava29=SaturdayRoomAvailability(room_id='PG2', time=17, status = "")
sava30=SaturdayRoomAvailability(room_id='PG2', time=18, status = "")
sava31=SaturdayRoomAvailability(room_id='PG2', time=19, status = "")
sava32=SaturdayRoomAvailability(room_id='PG2', time=20, status = "")
sava33=SaturdayRoomAvailability(room_id='CL', time=11, status = "")
sava34=SaturdayRoomAvailability(room_id='CL', time=14, status = "")
sava35=SaturdayRoomAvailability(room_id='CL', time=15, status = "")
sava36=SaturdayRoomAvailability(room_id='CL', time=18, status = "")
sava37=SaturdayRoomAvailability(room_id='CL', time=19, status = "")

db.session.add(sava1)
db.session.commit()
db.session.add(sava2)
db.session.commit()
db.session.add(sava3)
db.session.commit()
db.session.add(sava4)
db.session.commit()
db.session.add(sava5)
db.session.commit()
db.session.add(sava6)
db.session.commit()
db.session.add(sava7)
db.session.commit()
db.session.add(sava8)
db.session.commit()
db.session.add(sava9)
db.session.commit()
db.session.add(sava10)
db.session.commit()
db.session.add(sava11)
db.session.commit()
db.session.add(sava12)
db.session.commit()
db.session.add(sava13)
db.session.commit()
db.session.add(sava14)
db.session.commit()
db.session.add(sava15)
db.session.commit()
db.session.add(sava16)
db.session.commit()
db.session.add(sava17)
db.session.commit()
db.session.add(sava18)
db.session.commit()
db.session.add(sava19)
db.session.commit()
db.session.add(sava20)
db.session.commit()
db.session.add(sava21)
db.session.commit()
db.session.add(sava22)
db.session.commit()
db.session.add(sava23)
db.session.commit()
db.session.add(sava24)
db.session.commit()
db.session.add(sava25)
db.session.commit()
db.session.add(sava26)
db.session.commit()
db.session.add(sava27)
db.session.commit()
db.session.add(sava28)
db.session.commit()
db.session.add(sava29)
db.session.commit()
db.session.add(sava30)
db.session.commit()
db.session.add(sava31)
db.session.commit()
db.session.add(sava32)
db.session.commit()
db.session.add(sava33)
db.session.commit()
db.session.add(sava34)
db.session.commit()
db.session.add(sava35)
db.session.commit()
db.session.add(sava36)
db.session.commit()
db.session.add(sava37)
db.session.commit()

