from app import db
from app.models import Course, Day, Room, CourseCount

'''
day1 = Day(day_id="Mon",day_name="Monday")
day2 = Day(day_id="Tues",day_name="Tuesday")
day3 = Day(day_id="Wed",day_name="Wednesday")
day4 = Day(day_id="Thur",day_name="Thursday")
day5 = Day(day_id="Fri",day_name="Friday")
day6 = Day(day_id="Sat",day_name="Saturday")

db.session.add(day1)
db.session.commit()
db.session.add(day2)
db.session.commit()
db.session.add(day3)
db.session.commit()
db.session.add(day4)
db.session.commit()
db.session.add(day5)
db.session.commit()
db.session.add(day6)
db.session.commit()

course1 = Course(course_id="COMP2211", course_name="Analysis of Algorithms")
course2 = Course(course_id="COMP2201", course_name="Discrete Mathematics")
course3 = Course(course_id="COMP2190", course_name="Net-Centric Computing")
course4 = Course(course_id="COMP3191", course_name="Principles of Computer Networking")
course5 = Course(course_id="COMP3702", course_name="Theory of Computations")
course6 = Course(course_id="COMP3161", course_name="Database Management Systems")
course7 = Course(course_id="INFO2100", course_name="Math and Statistics for IT")
course8 = Course(course_id="INFO2110", course_name="Data Structures for IT")
course9 = Course(course_id="INFO3155", course_name="Information Assurance and Security")
course10 = Course(course_id="INFO3180", course_name="Dynamic Web Develoopment 2")

db.session.add(course1)
db.session.commit()
db.session.add(course2)
db.session.commit()
db.session.add(course3)
db.session.commit()
db.session.add(course4)
db.session.commit()
db.session.add(course5)
db.session.commit()
db.session.add(course6)
db.session.commit()
db.session.add(course7)
db.session.commit()
db.session.add(course8)
db.session.commit()
db.session.add(course9)
db.session.commit()
db.session.add(course10)
db.session.commit()

room1 = Room(room_id = "SLT1", room_name = "Science Lecture Theatre 1")
room2 = Room(room_id = "SLT2", room_name = "Science Lecture Theatre 2")
room3 = Room(room_id = "SLT3", room_name = "Science Lecture Theatre 3")
room4 = Room(room_id = "CR1", room_name = "Computing Tutorial 1")
room5 = Room(room_id = "CR2", room_name = "Computing Tutorial 2")
room6 = Room(room_id = "PG1", room_name = "Postgraduate Lecture Room")
room7 = Room(room_id = "PG2", room_name = "Postgraduate Lab")
room8 = Room(room_id = "CL", room_name = "Computing Lecture Room")

db.session.add(room1)
db.session.commit()
db.session.add(room2)
db.session.commit()
db.session.add(room3)
db.session.commit()
db.session.add(room4)
db.session.commit()
db.session.add(room5)
db.session.commit()
db.session.add(room6)
db.session.commit()
db.session.add(room7)
db.session.commit()
db.session.add(room8)
db.session.commit()

course1 = CourseCount(course_id="COMP2211", count_tutors=0)
course2 = CourseCount(course_id="COMP2201", count_tutors=0)
course3 = CourseCount(course_id="COMP2190", count_tutors=0)
course4 = CourseCount(course_id="COMP3191", count_tutors=0)
course5 = CourseCount(course_id="COMP3702", count_tutors=0)
course6 = CourseCount(course_id="COMP3161", count_tutors=0)
course7 = CourseCount(course_id="INFO2100", count_tutors=0)
course8 = CourseCount(course_id="INFO2110", count_tutors=0)
course9 = CourseCount(course_id="INFO3155", count_tutors=0)
course10 = CourseCount(course_id="INFO3180", count_tutors=0)

db.session.add(course1)
db.session.commit()
db.session.add(course2)
db.session.commit()
db.session.add(course3)
db.session.commit()
db.session.add(course4)
db.session.commit()
db.session.add(course5)
db.session.commit()
db.session.add(course6)
db.session.commit()
db.session.add(course7)
db.session.commit()
db.session.add(course8)
db.session.commit()
db.session.add(course9)
db.session.commit()
db.session.add(course10)
db.session.commit()'''

